spring:
  data:
    mongodb:
      username: mdbuser
      password: mdbuser
      hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090